version: '3.8'

services:
  template_bot:
    build: .
    container_name: template_bot
    restart: unless-stopped
    volumes:
      - ${HOME}/TemplateBot/log:/log
      - ./config:/config
    env_file: config/.env
    networks:
      - reverse-proxy
      - botapi
    depends_on:
      - telegram-bot-api
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:3000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "6"
      TELEGRAM_API_HASH: "eb06d4abfb49dc3eeb1aeb98ae0f581e"
      TELEGRAM_LOCAL: 1
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    networks:
      - botapi
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - telegram-bot-api-data:/var/lib/telegram-bot-api:ro
    networks:
      - botapi
      - reverse-proxy
    depends_on:
      - telegram-bot-api
    restart: unless-stopped

volumes:
  telegram-bot-api-data:

networks:
  reverse-proxy:
    external: true
  botapi:
    driver: bridge